### ISSUE TITLE
Missing checkpoint for stage1, 2 and 3

### ISSUE THREAD

**Issue by HencyChen** [NoOneUST/IS-MVSNet#2]
Hi @NoOneUST ,

Thanks for the great works.

I'm trying to run your code but find out there is only a 'backbone.ckpt' under the folder 'weights'. But in the code it seems we also need stage1, 2 and 3's checkpoints for loading.

If there's any possibility for you to provide the corresponded checkpoints?

Thanks a lot!

**Comment by NoOneUST** [comment]
Dear Hency,

Thank you for your interest in our paper. You may check the ReadMe file [here](https://github.com/NoOneUST/IS-MVSNet). The checkpoints are provided [here](https://hkustconnect-my.sharepoint.com/:f:/g/personal/lwangcg_connect_ust_hk/EjJEn_0ZGPNBlB3SRpc48b0BfVo3eS4VfCNNxB5LoAAWEQ?e=r0yeF3).

<img width="689" alt="image" src="https://user-images.githubusercontent.com/48406286/199259749-8b3bb9f2-cd2c-40f4-be84-3f5b5dc03e84.png">

**Comment by HencyChen** [comment]
Thanks for the quick reply. 

Sorry for another question.
The import in is_mvsnet.py is model_tnt_intermediate_backbone_new, however, the code name in folder src is model_tnt_intermediate_backbone. 
I'm wondering if the import module can be modified to model_tnt_intermediate_backbone directly in is_mvsnet.py?

Thanks again!

**Comment by NoOneUST** [comment]
I am unsure about this question because the code was written several months ago. You may first try this modification and test whether it works. I may have no time to check this problem these days because of some urgent deadlines. I will test it after finishing the dues.

**Comment by NoOneUST** [comment]
> Thanks for the quick reply.
> 
> Sorry for another question. The import in is_mvsnet.py is model_tnt_intermediate_backbone_new, however, the code name in folder src is model_tnt_intermediate_backbone. I'm wondering if the import module can be modified to model_tnt_intermediate_backbone directly in is_mvsnet.py?
> 
> Thanks again!

Have you solved this problem?
